### PR TITLE
This was done to solve the problem regarding duplicated links to the …

### PR DESCRIPTION
**Pull request by raphaeltimbo**
This was done to solve the problem regarding duplicated links to the vibesystem notebook and also the problem that this notebook was not rendered correctly when building the html files.

Basically what I did was:

1. Moved all notebooks to the folder /docs/tutorial
2. Deleted the JupyerNotebook folder and link
3. Deleted vibesystem.rst
4. Inside the /docs/tutorial/index.rst changed:

```
-   JupyterNotebooks/Beats.ipynb
 -   JupyterNotebooks/Vibration_System.ipynb
 +   Beats.ipynb
 +   Vibration_System.ipynb
```

One thing that I notice is that the markdown titles (when using # inside a notebook cell) creates links when generating the html files. Inside the vibesystem notebook we had 2 'titles' and because of that we were getting duplicated links on the website. 

I have built the html documentation and it was working.

@josephcslater , I think I did not break anything with this, but if you could please check before we merge this.

Another thing, would it be possible to add the /docs/_build to the .gitignore? I think we could add this to prevent adding these files to a commit after building the docs, since more than a hundred files are modified. Maybe we could keep these only in the gh-pages...

### CODE REVIEW

**Comment by josephcslater** [comment]
So, 2 points: 
1) I was indeed trying to keep notebooks at the top to be easily accessible for novice users. They are more hidden if they are in the documentation. I've considered a make item to duplicate them elsewhere, but that can create its own problems. This wouldn't be an issue if sphinx handled paths better. It's the one flaw in sphinx that I wish would be fixed. This was the reason for the links to the top level... to work around this shortcoming of sphinx. It is/was a hack. I don't know that there is a good solution right now. All options don't look good to me. 

2) I saw the duplicate titles and never got back to it. I was just thrilled to have it generating something useful that looked good. I'm likely to cause this issue again by accident, so please forgive when I forget.

**Comment by raphaeltimbo** [comment]
Ah, I was also having some trouble trying to understand how sphinx was handling the paths... But I really don't know what would be the best solution to this. Maybe an option could be to talk about the notebooks at the README? 

Regarding the duplicate titles, no problem.. I just mentioned here to keep track of this since it was something new to me.

**Comment by josephcslater** [comment]
I redirected the links in my commits Sunday. I don't know a good solution. The links enabled the build but were a hack. We likely need demo notebooks at the top level in the future because the target audience is likely novice in both vibration and python.

**Comment by josephcslater** [comment]
I think it's prudent to set the notebooks in a separate folder by themselves so they can be easily identified, observed, and downloaded. Ideally one would be able to download the notebook from within the document as well. The "Show source" link is not useful for notebooks. Download notebook is something I've seen elsewhere, and I'd like to implement that in an easy and maintainable way.

**Pull request merged**
