### PR TITLE
Added frequency response plot

### PR DESCRIPTION
**Pull request by raphaeltimbo**
Added frequency response plot to the vibesystem file.
Some matplotlib parameters have been added at the top of the file to make a seaborn-white style for these plots.

### CODE REVIEW

**Comment by raphaeltimbo** [comment]
This one is failing on travis because I have added some f-string and they are not supported on python 3.5.
@josephcslater , do you want to keep support to 3.5? 
I think that people that are on python 3 are already using 3.6 and supporting only this one would not be a problem. But let me know what you think. In any case this is just a small function and it would be easy to just use some string formatting available in python 3.5.

**Comment by josephcslater** [comment]
> On May 1, 2017, at 5:46 PM, raphaeltimbo <notifications@github.com> wrote:
> 
> This one is failing on travis because I have added some f-string and they are not supported on python 3.5.
> @josephcslater <https://github.com/josephcslater> , do you want to keep support to 3.5?
> I think that people that are on python 3 are already using 3.6 and supporting only this one would not be a problem. But let me know what you think. In any case this is just a small function and it would be easy to just use some string formatting available in python 3.5.
> 
> 

I do for now. What is f-string? Is there a version workaround we can use?

**Comment by raphaeltimbo** [comment]
Instead of string formatting like:
```
value = 10
print('Value is {}'.format(value))
print('Value is %s' % value)
```
in 3.6 we can use f-strings:
```
value = 10
print(f'Value is {value}')
```

I will change this before merging to keep compatibility with 3.5.

**Comment by josephcslater** [comment]
Cool technique I will have to remember (f-strings).

**Comment by josephcslater** [comment]
Lines 351 and 352::

        rows = self.H.inputs  # inputs (mag and phase)
        cols = self.H.inputs  # outputs

a) I have to admit I do not understand what they are doing. It the .H simply the Hermitian?
b) In spite of the fact that I have no clue what they are doing, it is suspicious that they are the same. Here `rows` and `cols` will always be identical. That cannot be true.

**Comment by raphaeltimbo** [comment]
H is actually a scipy object for 'Continuous-time linear time invariant system'. I am using the letter H to relate it to transfer function.
The inputs and outputs attributes of this object give the number of inputs and outputs that we have for the system. So yes, this is wrong. I will update the code to self.H.outputs at line 352!

See #34 .

**Comment by josephcslater** [comment]
I'm not familiar with these in scipy. I have some reading to do. Not how I learned... learning off of you. 

Where is this in the scipy manual?

**Comment by raphaeltimbo** [comment]
Here you can get some information: https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.signal.lti.html

**Pull request merged**
