### PR TITLE
Notebooks organization

### PR DESCRIPTION
**Pull request by raphaeltimbo**
The purpose of this pull request is to address issue #49 .
The names for the tutorial notebooks have been modified to follow some convention. This organize things and make it easier to provide the links to download the notebooks.
Notebooks with examples have been moved to a specific folder. In the main page the examples toctree does not show the link for each notebook. I did this to avoid having several unrelated links in the main page, since this could make the main page a mess. 
Latter we can also add links inside the examples subpage to download these notebooks.

### CODE REVIEW

**Comment by josephcslater** [comment]
Looks good to me if you want to go ahead ane merge it.

**Comment by josephcslater** [comment]
I don't see the links to download the notebooks, though.

**Comment by raphaeltimbo** [comment]
In the front page they are at the bottom:
image

And inside the notebooks I am putting then at the top:
image

**Comment by josephcslater** [comment]
Ahh... I didn't see that. 

I might be looking in wrong places. I've been a bit scrambled with another project I'm working on. Consider my IQ to be a bit lower in the short term.

**Pull request merged**
